version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:12.22

jobs:
  build:
    executor: default
    working_directory: ~/workspace
    steps:
      - checkout

      - run: sudo apt-get update && sudo apt-get install -y nasm autoconf automake libtool dpkg libpng-dev g++

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
