version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:12.22

jobs:
  build:
    executor: default
    working_directory: ~/workspace
    steps:
      - checkout

      - run: sudo apk add make nasm autoconf automake libtool dpkg pkgconfig libpng libpng-dev g++

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build
