- title: Web Developer - Yuma Kitamura
  description: products.profile
  skills:
    - normalize.css
    - nekohack-ui
    - Gatsby.js
    - Gatsby.js PWA
    - AWS CodeBuild
    - AWS S3
    - AWS CloudFront
    - Circle CI
    - Github Actions
  image: https://i.imgur.com/sN5nHoS.jpg
- title: Web猫ブログ
  description: products.blog
  skills:
    - j-stylebook
    - Nuxt.js
    - Nuxt.js PWA
    - Contentful
    - AWS ECS
    - AWS Fargate
    - AWS CloudFront
    - Circle CI
    - Github Actions
  image: https://i.imgur.com/xuj6KVU.jpg
