- title: products.profile
  description: products.profile_description
  skills:
    - normalize.css
    - nekohack-ui
    - Gatsby.js
    - Gatsby.js PWA
    - AWS CodeBuild
    - AWS S3
    - AWS CloudFront
    - Circle CI
    - Github Actions
  image: https://i.imgur.com/sN5nHoS.jpg
  url: https://yuma-kitamura.nekohack.me/
- title: products.tech_blog
  description: products.tech_blog_description
  skills:
    - j-stylebook
    - Nuxt.js
    - Nuxt.js PWA
    - Contentful
    - AWS ECS
    - AWS Fargate
    - AWS CloudFront
    - Circle CI
    - Github Actions
  image: https://i.imgur.com/xuj6KVU.jpg
  url: https://webneko.dev/
- title: products.minna_de_blog
  description: products.minna_de_blog_description
  skills:
    - Vite
    - Vue
    - Github Issues
    - Github Actions
    - Vercel
  image: https://i.imgur.com/cUXoOHs.jpg
  url: https://ohayo.nekohack.me/
- title: products.flutterkaigi_2021
  description: products.flutterkaigi_2021_description
  skills:
    - Flutter
    - Flutter for Web (PWA)
    - Firebase hosting
  image: https://i.imgur.com/9xFIDzQ.jpg
  url: https://flutterkaigi.jp/
- title: products.vscodeconjp_2021
  description: products.vscodeconjp_2021_description
  skills:
    - Next.js (React)
    - CSS modules
    - Github Pages
  image: https://i.imgur.com/fOyWXX2.jpg
  url: https://vscode.github.io/conf2021/
