- id: 0
  title: Web Developer - Yuma Kitamura
  description: 
    技術ブログと切り分けて自身を紹介するため、2020年03月に開設した当プロフィールサイト。これまで自身を紹介する入り口として登壇・LTの掴みにしていたWeb猫ブログの位置付けが当プロフィールサイトにとって変わる。
  skills: 
    - Gatsby.js
    - Gatsby.js PWA
    - AWS CDK
    - AWS S3
    - AWS CloudFront
    - Github Actions
- id: 1
  title: Web猫ブログ
  description: 
    知見を発信するため、2018年10月に開設した個人ブログ。命名は自身の特徴である猫好きから、また一個人Webデベロッパとしてフロントエンドに長けていること、インフラにも大変興味があるところから来ている。<br/>当時Headless CMSの一つであるContentfulが走りを見せていたこと。おしごとの場面でも永続的なプロダクトに出会えず途中でおじゃんに終わってしまったことなど、外部の影響を一切受けない個人としてのプロダクトを持つことが急務となっていた背景があり、新たにNuxt.js (当時 v1.0.0-beta.13) をベースに製作を始めている。
  skills: 
    - Nuxt.js
    - Nuxt.js PWA
    - Contentful
    - AWS ECS
    - AWS Fargate
    - Travis CI
    - Github Actions
  links: 
    - Web猫ブログに型安全を
      # url: https://master.d1kgb4480wljkh.amplifyapp.com/
    - Web猫ブログにGraphQLを導入してみた話
      # url: https://master.d1k81nysz2qoq8.amplifyapp.com/
    - Web猫ブログで問い合わせにFirestoreを採用した話
      # url: https://master.d1k6flsnxj32sh.amplifyapp.com/
    - Contentful製ブログでGoogle Adsenseが使えるようになるまで
      # url: https://master.d1k61oei78g67d.amplifyapp.com/
