- title: Web Developer - Yuma Kitamura
  description: yuukit_me
  skills:
    - nekohack-ui
    - Gatsby.js
    - Gatsby.js PWA
    - AWS CodeBuild
    - AWS S3
    - AWS CloudFront
    - Circle CI
    - Github Actions
- title: Web猫ブログ
  description: webneko_blog
  skills:
    - j-stylebook
    - Nuxt.js
    - Nuxt.js PWA
    - Contentful
    - AWS ECS
    - AWS Fargate
    - AWS CloudFront
    - Circle CI
    - Github Actions
