- title: products.design_system
  description:
    - products.design_system_description
  url: https://normalize.nekohack.me/
  sub:
    - title: products.react_design_system
      skills:
        - React
        - Styled Components
        - Vercel
    - title: products.vue_design_system
      skills:
        - Vue
        - Scoped CSS
        - Vercel
- title: products.profile
  description:
    - products.profile_description_1
    - products.profile_description_2
  skills:
    - normalize.css
    - nekohack-ui
    - Gatsby.js
    - Gatsby.js PWA
    - AWS CodeBuild
    - AWS S3
    - AWS CloudFront
    - Circle CI
    - Github Actions
  #image: https://i.imgur.com/sN5nHoS.jpg
  image: https://yuma-kitamura.nekohack.me/og/yuma_kitamura-nekohack-me.jpg
  url: https://yuma-kitamura.nekohack.me/
- title: products.tech_blog
  description:
    - products.tech_blog_description_1
    - products.tech_blog_description_2
    - products.tech_blog_description_3
  skills:
    - j-stylebook
    - Nuxt.js
    - Nuxt.js PWA
    - Contentful
    - AWS ECS
    - AWS Fargate
    - AWS CloudFront
    - Circle CI
    - Github Actions
  #image: https://i.imgur.com/xuj6KVU.jpg
  image: https://yuma-kitamura.nekohack.me/og/webneko-blog.jpg
  url: https://webneko.dev/
- title: products.minna_de_blog
  description:
    - products.minna_de_blog_description
  skills:
    - Vite
    - Vue
    - Github Issues
    - Github Actions
    - Vercel
  #image: https://i.imgur.com/cUXoOHs.jpg
  image: https://yuma-kitamura.nekohack.me/og/ohayo-engineer.jpg
  url: https://ohayo.nekohack.me/
- title: products.flutterkaigi_2021
  description:
    - products.flutterkaigi_2021_description
  skills:
    - Flutter
    - Flutter for Web (PWA)
    - Firebase hosting
  #image: https://i.imgur.com/9xFIDzQ.jpg
  image: https://yuma-kitamura.nekohack.me/og/flutterkaigi-2021.jpg
  url: https://flutterkaigi.jp/
- title: products.vscodeconjp_2021
  description:
    - products.vscodeconjp_2021_description
  skills:
    - Next.js (React)
    - CSS modules
    - Github Pages
  #image: https://i.imgur.com/fOyWXX2.jpg
  image: https://yuma-kitamura.nekohack.me/og/vscodejpcon-2021.jpg
  url: https://vscode.github.io/conf2021/
