- title: products.profile
  description: products.profile_description
  skills:
    - normalize.css
    - nekohack-ui
    - Gatsby.js
    - Gatsby.js PWA
    - AWS CodeBuild
    - AWS S3
    - AWS CloudFront
    - Circle CI
    - Github Actions
  image: https://i.imgur.com/sN5nHoS.jpg
- title: products.tech_blog
  description: products.tech_blog_description
  skills:
    - j-stylebook
    - Nuxt.js
    - Nuxt.js PWA
    - Contentful
    - AWS ECS
    - AWS Fargate
    - AWS CloudFront
    - Circle CI
    - Github Actions
  image: https://i.imgur.com/xuj6KVU.jpg
